#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
source "$(dirname "$SCRIPT_DIR")/utils.bash"

GSHELL="org.gnome.shell.keybindings"
WM="org.gnome.desktop.wm.keybindings"
MEDIA="org.gnome.settings-daemon.plugins.media-keys"
MOD="<Super>"
PKGS=(
  gnome-shell-extension-appindicator
)

gsettings_set() {
  local space="$1"
  local action="$2"
  local binding="$3"

  gsettings set "$space" "$action" "['$binding']"
}

add_custom_keybinding() {
  local name="$1"
  local command="$2"
  local binding="$3"
  local id="$4"

  local base="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/$id/"
  local current
  local new

  current=$(gsettings get "$MEDIA" custom-keybindings)

  if [[ "$current" == "@as []" ]]; then
    new="['$base']"
  elif [[ "$current" != *"$base"* ]]; then
    new="${current%]}"
    new="${new}, '$base']"
  else
    new="$current"
  fi

  if [[ "$new" != "$current" ]]; then
    gsettings set "$MEDIA" custom-keybindings "$new"
  fi

  gsettings set "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$base" name "$name"
  gsettings set "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$base" command "$command"
  gsettings set "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$base" binding "$binding"
}

set_keybindings() {
  # Windows
  gsettings_set "$WM" close "${MOD}q"
  gsettings_set "$WM" toggle-fullscreen "${MOD}f"

  gsettings set "$GSHELL" toggle-message-tray "[]"
  gsettings_set "$WM" toggle-maximized "${MOD}m"

  # Navigation
  gsettings_set "$WM" cycle-windows "${MOD}k"

  # Launchers
  gsettings_set "$MEDIA" home "${MOD}e"
  gsettings_set "$MEDIA" www "${MOD}b"

  # Workspace switching
  gsettings_set "$WM" switch-to-workspace-1 "${MOD}1"
  gsettings_set "$WM" switch-to-workspace-2 "${MOD}2"
  gsettings_set "$WM" switch-to-workspace-3 "${MOD}3"

  # Move current window to workspace
  gsettings_set "$WM" move-to-workspace-1 "${MOD}<Shift>1"
  gsettings_set "$WM" move-to-workspace-2 "${MOD}<Shift>2"
  gsettings_set "$WM" move-to-workspace-3 "${MOD}<Shift>3"

  # Disable default GNOME app switching on Super+1..3
  gsettings set "$GSHELL" switch-to-application-1 "[]"
  gsettings set "$GSHELL" switch-to-application-2 "[]"
  gsettings set "$GSHELL" switch-to-application-3 "[]"

  # Launch Ghostty
  add_custom_keybinding "Ghostty" "ghostty" "${MOD}Return" "ghostty"
}

reset_keybindings() {
  gsettings reset-recursively "$GSHELL"
  gsettings reset-recursively "$WM"
  gsettings reset-recursively "$MEDIA"
}

main() {
  if [[ $# -eq 0 ]]; then
    exit 1
  fi

  case "$1" in
  --setup)
    pacman_install "${PKGS[@]}"
    set_keybindings
    ;;
  --reset)
    reset_keybindings
    ;;
  *)
    exit 1
    ;;
  esac
}

main "$@"