#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
RESOURCES="$SCRIPT_DIR/installer.d"
STOWRC="$SCRIPT_DIR/configs/.stowrc"

source "$RESOURCES/utils.bash"

STOW_PKGS=(
  bash
  chromium
  ghostty
  git
  starship
  systemd
  bin
)

declare -A GIT_REPOS=(
)

install_pkgs() {
  local -a pkgs
  local pkg_list file_name
  local pkgs_path="$RESOURCES/pkgs"

  for pkg_list in "$pkgs_path"/common/*.list; do
    [[ -f "$pkg_list" ]] || continue
    mapfile -t pkgs < <(grep -v '^\s*#\|^\s*$' "$pkg_list")
    pacman_install "${pkgs[@]}"
  done

  for file_name in "$@"; do
    pkg_list="$pkgs_path/extra/$file_name.list"
    [[ -f "$pkg_list" ]] || continue

    mapfile -t pkgs < <(grep -v '^\s*#\|^\s*$' "$pkg_list")
    pacman_install "${pkgs[@]}"
  done
}

git_clone() {
  local -n repos=$1
  local url_prefix="git@github.com:"

  for repo in "${!repos[@]}"; do
    dest="${repos[$repo]}"

    if [[ -e "$dest" ]]; then
      log_warn "Skipping $repo: $dest already exists"
      continue
    fi

    log_info "Cloning $repo to $dest..."
    git clone "$url_prefix$repo" "$dest"
  done
}

stow_setup() {
  cat >"$STOWRC" <<STOW
--target="$HOME"
STOW
}

stow_install() {
  (
    cd "$(dirname "$STOWRC")"
    for pkg in "$@"; do
      log_info "Stowing $pkg..."
      stow "$pkg"
    done
  )
}

usage() {
  cat <<USAGE
Usage: $(basename "$0") [OPTIONS]

Sets up the system by installing packages, cloning dotfiles and linking config files via stow.

Options:
  -p, --package   Include extra packages
  -r, --reset     Reset configuration instead of applying it
  -h, --help      Show this message and exit
USAGE
}

main() {
  local -a extra_pkgs
  local mode="--setup"
  while [[ $# -gt 0 ]]; do
    case "$1" in
    -p | --package)
      extra_pkgs+=("$2")
      shift 1
      ;;
    -r | --reset)
      mode="--reset"
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
    esac
    shift 1
  done

  # Cache sudo credentials
  sudo -v

  # Full system upgrade
  sudo pacman -Syu --noconfirm

  # Install packages
  install_pkgs "${extra_pkgs[@]}"
  git_clone GIT_REPOS

  # Backup .bashrc and link config files
  local rc_file="$HOME/.bashrc"
  if [[ -f "$rc_file" ]]; then
    mv "$rc_file" "${rc_file}.bak"
  fi

  mkdir -p "$HOME/.config/systemd/user/"
  mkdir -p "$HOME/.local/bin/"

  if [[ ! -f "$STOWRC" ]]; then
    stow_setup
  fi
  stow_install "${STOW_PKGS[@]}"

  # Setup desktop via custom script
  case "${XDG_CURRENT_DESKTOP:-}" in
  *GNOME*)
    log_info "Detected GNOME desktop"
    log_info "Setting up GNOME..."
    "$RESOURCES/desktop/gnome" "$mode"
    ;;
  esac
}

main "$@"
